version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: nestjs_container
    ports:
      # Nestjs
      - "3005:3005"
      # prisma studio
      - "5555:5555"
    volumes:
      - "./app/backend:/home/node/nestjs"
      - "backend_node_modules:/home/node/nestjs/node_modules"
    tty: true
    stdin_open: true

  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    container_name: postgres_container
    ports:
    # postgres
    - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
    restart: always

volumes:
  backend_node_modules: